server:
  port: 3030
spring:
  application:
    name: budin-user-center
  redis:
    host: 10.112.49.187
    port: 6379
    password: dxq-py36
    timeout: 1000
    lettuce:
      pool:
        max-active: 8
  datasource:
    name: debian-budin-center
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.112.49.187:3306/budin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: dxq
    password: dxq-py36
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4000/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
mybatis:
  mapper-locations: classpath*:indiv/budin/mapper/*Mapper*.xml

config:
  jwt:
    header: Authorization
    tokenPrefix: Budin  #token前缀
    secret: budin2021D1xSa13d41 #密钥
    timeUnit: second # 单位分钟
    expireTime: 4 #token有效时间 (分钟) 建议一小时以上
    restTime: 1
  email:
    host:
    serverAddress:
    authPass:
