server:
  port: 3020
spring:
  application:
    name: budin-file-service
  datasource:
    name: debian-budin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.112.49.187:3306/budin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: dxq
    password: dxq-py36
    driver-class-name: com.mysql.cj.jdbc.Driver
minio:
  endpoint: http://10.112.49.187:9110 #Minio服务所在地址
  bucketName: none
  bucketDomain: none
  accessKey: minio-dxq #访问的key
  secretKey: dxq-py36

mybatis:
  mapper-locations: classpath*:indiv/budin/mapper/*Mapper*.xml