budin:
  server:
    name: simple
    host: 127.0.0.1
    port: 9011
config:
  jwt:
    header: Authorization
    tokenPrefix: Budin  #token前缀
    secret: budin2021D1xSa13d41 #密钥
    timeUnit: second # 单位分钟
    expireTime: 4 #token有效时间 (分钟) 建议一小时以上
    restTime: 1