server:
  port: 3020
spring:
  application:
    name: budin-file-service
  datasource:
    name: database
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.112.49.187:3306/budin?serverTimezone=GMT%2B8&amp;characterEncoding=utf-8
    username: dxq
    password: dxq-py36
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper*.xml